transition to testthat 3e
tidymodels/tidypredict pull request #105
Opened 2022-04-20 12:59 UTC by simonpcouch

Mostly just a version bump and dropping `context`! Tests made good use of `expect_is`, and did so in a few different ways, so replaced with `expect_s3_class`, `expect_equal`, and `expect_type` depending on the situation.🌼

2022-04-20 13:10 UTC, simonpcouch commented
Some build failures addressed in #106, some related to:

```
   x Cannot install packages:
  * local::.: Can't install dependency randomForest
  * randomForest: Needs R >= 4.1.0 
```

2022-04-20 14:17 UTC, juliasilge commented
You might check out how you can handle randomForest not being available on older R, like [in hardhat](https://github.com/tidymodels/butcher/blob/main/.github/workflows/R-CMD-check.yaml).

2022-04-20 14:19 UTC, simonpcouch commented
Ah, I see! Thank you for passing this along—will mark #106 as draft and make those changes there.

2022-05-04 15:32 UTC, juliasilge requested changes
This is looking good! 🙌 

Part of what we need to get fixed in the very short term (see #104) are the tests for the generated SQL. Can you also find all the tests that are for generated SQL / dbplyr / etc and change those to snapshot tests?

2022-05-04 17:11 UTC, simonpcouch commented
Sure thing! Made that happen in [620e316](https://github.com/tidymodels/tidypredict/pull/105/commits/620e316f252a46792337cceeb76f861c68a3f84d)—now closes #104.

2022-05-04 18:56 UTC, simonpcouch commented
Ah, yes! Checking out those and other `expect_silent`s, these don’t seem particularly vulnerable to dependency breakage in a meaningful way and are worth checking more thoroughly. Converted those to `expect_snapshot`. :)

2022-05-04 23:50 UTC, juliasilge commented on tests/testthat/_snaps/earth.md
> +      list()
This one seems like it does not actually work? Can you double check that this is a bug? I [confirm that `tidypredict_fit(model)` and `tidypredict_sql(model, dbplyr::simulate_odbc())` both work](https://tidypredict.tidymodels.org/articles/mars.html), but it seems like `model %>% parse_model() %>% tidypredict_fit()` does not work for earth?

If you can confirm this, then let's open an issue about fixing this problem in another PR later.

2022-05-04 23:51 UTC, juliasilge approved these changes

2022-05-08 23:08 UTC, simonpcouch commented
Ah, and some of these snapshots ended up failing on Actions. Looks like some line wrapping issues, but some actual differences in model results (maybe RNG?).

2022-05-08 23:26 UTC, simonpcouch commented on tests/testthat/_snaps/earth.md
> +      list()
Confirming that I see this locally as well.🤔

2022-05-08 23:54 UTC, simonpcouch commented
Okay, doesn't look like the failing snapshot tests are RNG-, rounding error-, or line wrapping-related.

I'd be glad to revert the failing tests and file issues if that seems like a good route forward! Will defer to others with more expertise on this package to debug those snapshot differences (if they indeed are issues at all).

2022-05-09 20:46 UTC, simonpcouch commented
Okay, just reverted a few of those tests!

Thumbs up from me on merging if this looks good to you—filing an issue re: the snapshot failures we saw in a moment.

2022-05-09 21:06 UTC, juliasilge approved these changes
Looking good! 🚀

2022-05-09 21:12 UTC, merged